# Generated by Django 5.2.7 on 2025-10-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aduan',
            fields=[
                ('id_aduan', models.AutoField(primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('image', models.ImageField(upload_to='aduan_images/')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('customer_id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('vendor_id_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
            options={
                'verbose_name_plural': 'Aduan',
            },
        ),
    ]
