# Generated by Django 5.2.9 on 2025-12-16 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(primary_key=True, serialize=False)),
                ('no_transaksi', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('nominal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('customer_id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('vendor_id_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jenis_transaksi', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('customer_id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('transaction_no_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
