# Generated by Django 5.2.7 on 2025-10-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('no_transaksi', models.CharField(max_length=255)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jenis_transaksi', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('customer_id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
