# Generated by Django 5.2.9 on 2025-12-17 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='vendor_id_vendor',
        ),
        migrations.AddField(
            model_name='transaction',
            name='jasa_id_jasa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.jasa'),
        ),
    ]
