# Generated by Django 5.2.9 on 2025-12-17 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_vendor_id_vendor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='transaction_no_transaksi',
            new_name='transaction_id_transaksi',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer_id_customer',
        ),
    ]
