# Generated by Django 5.2.9 on 2025-12-17 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_transaction_no_transaksi_payment_transaction_id_transaksi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id_transaksi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
    ]
