# Generated by Django 5.2.7 on 2025-10-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jasa',
            fields=[
                ('id_jasa', models.AutoField(primary_key=True, serialize=False)),
                ('name_jasa', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='jasa_images/')),
                ('deskripsi', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('vendor_id_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.vendor')),
            ],
            options={
                'verbose_name_plural': 'Jasa',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id_review', models.AutoField(primary_key=True, serialize=False)),
                ('komentar', models.TextField()),
                ('rating', models.IntegerField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('customer_idcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('jasa_id_jasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.jasa')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
