# Generated by Django 5.2.9 on 2025-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasa',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='jasa',
            name='status',
            field=models.CharField(default='Published', max_length=50),
        ),
    ]
