# Generated by Django 5.2.9 on 2025-12-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_jasa_harga_jasa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasa',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
