# Generated by Django 5.2.9 on 2025-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default='aktif', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='aktif', max_length=50),
        ),
    ]
